export type СurrencyBackendType = {
    SPREAD: number;
    HIGH: number;
    LOW: number;
    OPEN: number;
    LAST: number;
    LASTCNGTOLASTWAPRICE: number;
    VALTODAY: number;
    VOLTODAY: number;
    VALTODAY_USD: number;
    WAPRICE: number;
    WAPTOPREVWAPRICE: number;
    CLOSEPRICE: number;
    NUMTRADES: number;
    TRADINGSTATUS: string;
    UPDATETIME: string;
    BOARDID: string;
    SECID: string;
    WAPTOPREVWAPRICEPRCNT: number;
    CHANGE: number;
    LASTCHANGEPRCNT: number;
    VALUE: number;
    VALUE_USD: number;
    SEQNUM: number;
    QTY: number;
    TIME: string;
    PRICEMINUSPREVWAPRICE: number;
    LASTCHANGE: number;
    LASTTOPREVPRICE: number;
    VALTODAY_RUR: number;
    SYSTIME: string;
    MARKETPRICE: number;
    MARKETPRICETODAY: number;
    MARKETPRICE2: number;
    LOPENPRICE: number;
};

export type СurrencyType = {
    text: string;
    value: number;
    time: string;
};
